<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0, width=device-width" />
	<link rel="stylesheet" href="./style/index.scss">
	<title>Titan</title>
</head>

    
<body>

	<!--******************************* HEADER ********************************************************-->
	<header class="header maintheme">    
		<?php if (\Session::hasFlashes('error')): ?>
			<div class="account-message">
				<div  id='currentMessage'>
					<div class="text">
						<?php foreach (\Session::getFlashes('error') as $message): ?>
							<p><?=$message?></p>
						<?php endforeach?>
					</div>
				</div>
			</div>
		<?php endif?>

		<?php if (\Session::hasFlashes('success')): ?>
			<div id='successMessage'>
				<div class="message message-element message-success ok">
					<div class="text">
						<?php foreach (\Session::getFlashes('success') as $message): ?>
							<p><?=$message?></p>
						<?php endforeach?>
					</div>
				</div>
			</div>
		<?php endif?>
	</header>
	
	<!--******************************* MAIN PAGE HOME ********************************************************-->
	
	<main class="container">

	
		
		<form class='form' action="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=create" method="POST">
			

			
			<div class="logo"></div>
			<h1>Inscrivez-vous pour faire partie de premiers touristes de Titan, la fameuse lune de Saturne !</h1>
			
			<label class="nameLab" for='name'>Prénom</label>
			<input class="nameInp" name="name" type="text">
		
		
			<label class="surnameLab" for='surname'>Nom</label>
			<input class="surnameInp" name="surname" type="text" required>
		
		
			<label class="emailLab" for='email'>Email</label>
			<input class="emailInp" name="email" type="text" required>
		

		
			<label class="subscribeLab" for="subscribeNews">J'accepte de m'inscrire à la newsletter de Titan</label>
			<input class="check" type="checkbox" id="subscribeNews" name="subscribe" value="newsletter">
		
			<button class="button">Valider mon inscription</button>
			
		</form>
		
    </main>
	
	
	<!--******************************* FOOTER ********************************************************-->
	

	<footer class="footer">
	</footer>
		

</body>
</html>