<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0, width=device-width" />
	<link rel="stylesheet" href="./style/index.scss">
    <link rel="stylesheet" href="./style/fontawesome-free-5.15.4-web/css/fontawesome.css">
	<title>Titan</title>
</head>

    
<body>

	<!--******************************* HEADER ********************************************************-->
	<header class="header maintheme">    
		
	
	<!--******************************* MAIN PAGE HOME ********************************************************-->
	
	<main class="container">
		
		
			
			<div class="logo"></div>
			<h1 class="message">Votre inscription a bien été prise en compte pour faire partie des premiers touristes de Titan, la chance !</h1>
			
			
		
    </main>git
	
	
	<!--******************************* FOOTER ********************************************************-->
	

	<footer class="footer">
	</footer>
		

</body>
</html>